// src/components/TryMirror.jsx
import React, { useEffect, useRef, useState, useCallback } from 'react'
import { createPortal } from 'react-dom'
import { Button, Icon, IconButton } from '../ds/index.js'
import { useFaceLandmarker } from './useFaceLandmarker.js'
import { resolveTryonAsset } from './tryon/config.js'
// GlassesEngine (and its Three.js dependency) is loaded on demand — only when a
// product actually has a 3D model — so it never weighs down the storefront bundle.
let _EnginePromise = null
const loadEngine = () => (_EnginePromise ||= import('./tryon/GlassesEngine.js').then((m) => m.GlassesEngine))

/**
 * TryMirror — per-product virtual try-on with three input modes:
 *   1) Live camera   2) Upload photo   3) Upload video
 *
 * All processing is in-browser (MediaPipe Face Landmarker, no key, no upload).
 * The overlay follows a per-colour fallback chain (see TRYON_NOTES.md):
 *   1) a real 3D frame model (GlassesEngine / product.tryMirrorModel), else
 *   2) a transparent-PNG frame (product.tryMirrorImg), else
 *   3) a drawn vector rendition from the product's shape + colours.
 * The chosen frame size persists to the cart as a custom size.
 *
 * Props:
 *   open, onClose        modal visibility
 *   product              the opened product (id, brand, name, shape, colors…)
 *   frameAsset           optional legacy single-PNG override (string)
 *   strings              i18n bundle (root.product)
 *   onAddToCart(pct)     called with e.g. "110%" — persisted as line customSize
 */

const BASE_MULT = 2.15    // frame width ≈ 2.15 × outer-eye distance (see asset notes)
const EMA_ALPHA = 0.5     // landmark smoothing factor for live/video (0..1)
const MAX_IMG = 1600      // downscale uploaded photos to this max dimension

// Head pose (yaw/pitch/roll) from MediaPipe's 4×4 column-major transform matrix.
function headAngles(mat) {
  if (!mat) return { yaw: 0, pitch: 0 }
  const m = mat.data || mat
  const r00 = m[0], r10 = m[1], r20 = m[2], r21 = m[6], r22 = m[10]
  const sy = Math.hypot(r00, r10)
  return { pitch: Math.atan2(r21, r22), yaw: Math.atan2(-r20, sy) }
}

const ema = (prev, cur, a) => (prev == null ? cur : { x: prev.x + a * (cur.x - prev.x), y: prev.y + a * (cur.y - prev.y) })

// Vector fallback style (only when a product has no transparent-PNG asset yet).
function vectorStyle(product, color) {
  const shape = String(product?.shape || '').toLowerCase()
  if (shape.includes('aviator')) return { stroke: color || '#b8862f', lw: 0.05, rx: 0.30, ry: 0.25, tint: 'rgba(120,90,30,0.16)' }
  if (shape.includes('round') || shape.includes('oval')) return { stroke: color || '#2b2b2b', lw: 0.055, rx: 0.26, ry: 0.26, tint: 'rgba(20,20,25,0.10)' }
  return { stroke: color || '#141414', lw: 0.075, rx: 0.31, ry: 0.23, tint: null }
}
function drawVector(ctx, landmarks, W, H, st, scale) {
  const P = (i) => ({ x: landmarks[i].x * W, y: landmarks[i].y * H })
  if (!landmarks[33] || !landmarks[263]) return
  const rO = P(33), lO = P(263), rIn = P(133) || rO, lIn = P(362) || lO, rEar = P(234) || rO, lEar = P(454) || lO
  const rEye = { x: (rO.x + rIn.x) / 2, y: (rO.y + rIn.y) / 2 }
  const lEye = { x: (lO.x + lIn.x) / 2, y: (lO.y + lIn.y) / 2 }
  const span = Math.hypot(lO.x - rO.x, lO.y - rO.y)
  const ang = Math.atan2(lO.y - rO.y, lO.x - rO.x)
  const ux = Math.cos(ang), uy = Math.sin(ang)
  const rx = span * st.rx * scale, ry = span * st.ry * scale, lw = Math.max(1.5, span * st.lw * scale)
  ctx.save(); ctx.lineJoin = 'round'; ctx.lineCap = 'round'; ctx.strokeStyle = st.stroke; ctx.lineWidth = lw
  for (const c of [rEye, lEye]) { ctx.beginPath(); ctx.ellipse(c.x, c.y, rx, ry, ang, 0, Math.PI * 2); if (st.tint) { ctx.fillStyle = st.tint; ctx.fill() } ctx.stroke() }
  ctx.beginPath(); ctx.moveTo(rEye.x + ux * rx, rEye.y + uy * rx); ctx.lineTo(lEye.x - ux * rx, lEye.y - uy * rx); ctx.stroke()
  ctx.beginPath(); ctx.moveTo(rEye.x - ux * rx, rEye.y - uy * rx); ctx.lineTo(rEar.x, rEar.y); ctx.stroke()
  ctx.beginPath(); ctx.moveTo(lEye.x + ux * rx, lEye.y + uy * rx); ctx.lineTo(lEar.x, lEar.y); ctx.stroke()
  ctx.restore()
}

// PNG overlay: centre on nose-bridge (168), rotate to eye tilt, scale by eye
// distance × BASE_MULT × userSize, wrap with a yaw perspective squeeze.
function drawPng(ctx, img, p33, p263, p168, mat, scale) {
  const dx = p263.x - p33.x, dy = p263.y - p33.y
  const eyeDist = Math.hypot(dx, dy)
  const roll = Math.atan2(dy, dx)
  const { yaw, pitch } = headAngles(mat)
  const width = eyeDist * BASE_MULT * scale
  const height = width * (img.naturalHeight / img.naturalWidth || 0.4)
  const squeeze = Math.max(0.45, Math.cos(yaw))         // narrows as the head turns
  const yawShift = Math.sin(yaw) * eyeDist * 0.15        // frame follows the nose
  const pitchShift = Math.sin(pitch) * eyeDist * 0.12
  ctx.save()
  ctx.translate(p168.x + yawShift, p168.y + pitchShift)
  ctx.rotate(roll)
  ctx.scale(squeeze, 1)
  ctx.drawImage(img, -width / 2, -height * 0.5, width, height)
  ctx.restore()
}

const MODES = [
  { key: 'live', icon: 'camera', label: 'modeLive' },
  { key: 'photo', icon: 'user', label: 'modePhoto' },
  { key: 'video', icon: 'smartphone', label: 'modeVideo' },
]

export function TryMirror({ open, onClose, product, frameAsset, strings, onAddToCart }) {
  const p = product || {}
  const t = strings

  const { status, get: getEngine, setRunningMode, retry } = useFaceLandmarker(open)

  const [mode, setMode] = useState('live')
  const [size, setSize] = useState(1)
  const [colorIdx, setColorIdx] = useState(0)
  const [err, setErr] = useState('')
  const [hasFace, setHasFace] = useState(true)
  const [sourceLoaded, setSourceLoaded] = useState(false)
  const [playing, setPlaying] = useState(false)
  const [progress, setProgress] = useState(0)

  const videoRef = useRef(null)
  const canvasRef = useRef(null)
  const photoInputRef = useRef(null)
  const videoInputRef = useRef(null)
  const frameRef = useRef(null)          // loaded 2D PNG Image (or null)
  const engineRef = useRef(null)         // lazily-created 3D GlassesEngine (or null)
  const modelUrlRef = useRef('')         // active colour's 3D model URL (cleared if it fails to load)
  const pngUrlRef = useRef('')           // active colour's 2D PNG URL (whether or not loaded yet)
  const metaRef = useRef({})             // active colour's tryMirrorMeta
  const paintRef = useRef(null)          // latest paint() (avoids hook ordering)
  const sourceRef = useRef(null)         // current drawable: <video> or <img>
  const photoDetRef = useRef(null)       // { l, mat } for the static photo
  const smoothRef = useRef({})
  const rafRef = useRef(null)
  const runningRef = useRef(false)
  const streamRef = useRef(null)
  const objUrlRef = useRef(null)
  const lastTsRef = useRef(0)
  const openRef = useRef(open)
  const sizeRef = useRef(1); sizeRef.current = size
  const colorRef = useRef(0); colorRef.current = colorIdx
  const faceRef = useRef(true)

  const sizePct = `${Math.round(size * 100)}%`
  useEffect(() => { openRef.current = open }, [open])

  const setFace = (v) => { if (faceRef.current !== v) { faceRef.current = v; setHasFace(v) } }
  const smoothReset = () => { smoothRef.current = {} }
  const prepCanvas = (w, h) => { const c = canvasRef.current; if (c) { c.width = w; c.height = h } }

  // Resolve + load the selected colour's try-on assets (fallback chain:
  // 3D model → 2D PNG → drawn vector). Runs on open and on every colour change.
  const colorHex = (p.colors || [])[colorIdx]
  // Legacy `frameAsset` (a single PNG URL) still works as an all-colours override.
  const legacy = typeof frameAsset === 'string' && frameAsset ? { ...p, tryMirrorImg: frameAsset } : p
  const { model: modelUrl, png: pngUrl, meta } = resolveTryonAsset(legacy, colorHex)
  useEffect(() => {
    if (!open) return
    let alive = true
    metaRef.current = meta
    // Record what this colour HAS (used by the paint fallback chain) up front,
    // so a still-loading asset never falls through to the vector tier.
    pngUrlRef.current = pngUrl
    modelUrlRef.current = modelUrl
    // 2D PNG (fallback + shown while a 3D model is still loading).
    frameRef.current = null
    if (pngUrl) {
      const img = new Image(); img.crossOrigin = 'anonymous'
      img.onload = () => { if (alive) { frameRef.current = img; repaintPhoto() } }
      img.onerror = () => { if (alive && frameRef.current === img) { frameRef.current = null; console.warn('[tryon] frame PNG failed to load:', pngUrl) } }
      img.src = pngUrl
    }
    // 3D model (primary). Create the WebGL engine lazily — only when a model
    // asset exists — and degrade gracefully (clear the model URL so the 2D/vector
    // tier takes over) if WebGL is unavailable or the model fails to load.
    if (modelUrl) {
      const giveUp = () => { if (alive && modelUrlRef.current === modelUrl) { modelUrlRef.current = ''; repaintPhoto() } }
      loadEngine().then((GlassesEngine) => {
        if (!alive) return
        if (!engineRef.current) { try { engineRef.current = new GlassesEngine(640, 480) } catch (e) { console.warn('[tryon] WebGL unavailable, using 2D overlay:', e?.message || e); giveUp(); return } }
        return engineRef.current.setModel(modelUrl).then((okModel) => {
          if (!alive) return
          if (!okModel) giveUp(); else repaintPhoto()
        })
      }).catch((e) => { console.warn('[tryon] engine load failed, using 2D overlay:', e?.message || e); giveUp() })
    }
    return () => { alive = false }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, modelUrl, pngUrl])

  // Repaint the static photo (live/video redraw themselves each frame).
  const repaintPhoto = useCallback(() => {
    if (photoDetRef.current && sourceRef.current) {
      const { l, mat } = photoDetRef.current
      paintRef.current && paintRef.current(l, mat, { smooth: false, detActive: true })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // ── shared paint ───────────────────────────────────────────────────────────
  const paint = useCallback((landmarks, mat, { smooth, detActive }) => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    const W = canvas.width, H = canvas.height
    ctx.clearRect(0, 0, W, H)
    if (sourceRef.current) { try { ctx.drawImage(sourceRef.current, 0, 0, W, H) } catch { /* not ready */ } }
    if (detActive) setFace(!!landmarks)
    const frameImg = frameRef.current
    const engine = engineRef.current
    const modelReady = engine && modelUrlRef.current && engine.hasModel(modelUrlRef.current)
    // On a dropped-detection frame, let the 3D engine hold/fade the last pose
    // (its faceHoldFrames logic) instead of instantly flickering off.
    if (!landmarks) {
      if (modelReady) { engine.resize(W, H); engine.update(null, metaRef.current, sizeRef.current, false); try { ctx.drawImage(engine.render(), 0, 0, W, H) } catch { /* gl not ready */ } }
      return
    }
    // Fallback chain: 3D model → 2D PNG → drawn vector. The vector tier keys off
    // whether the product HAS assets (refs), not transiently-cleared load state,
    // so it never flashes over a product that has a real model/PNG loading.
    if (modelReady && landmarks[33] && landmarks[263]) {
      // The 2D canvas is CSS-mirrored for Live; render the scene in video space
      // and let that single CSS flip apply — so pass mirrored=false here.
      engine.resize(W, H)
      engine.update(landmarks, metaRef.current, sizeRef.current, false)
      try { ctx.drawImage(engine.render(), 0, 0, W, H) } catch { /* gl not ready */ }
    } else if (frameImg && landmarks[33] && landmarks[263] && landmarks[168]) {
      let a = { x: landmarks[33].x * W, y: landmarks[33].y * H }
      let b = { x: landmarks[263].x * W, y: landmarks[263].y * H }
      let n = { x: landmarks[168].x * W, y: landmarks[168].y * H }
      if (smooth) { const s = smoothRef.current; a = s.a = ema(s.a, a, EMA_ALPHA); b = s.b = ema(s.b, b, EMA_ALPHA); n = s.n = ema(s.n, n, EMA_ALPHA) }
      drawPng(ctx, frameImg, a, b, n, mat, sizeRef.current)
    } else if (!pngUrlRef.current && !modelUrlRef.current) {
      // Last resort only — the product has no 3D and no 2D asset for this colour.
      drawVector(ctx, landmarks, W, H, vectorStyle(p, (p.colors || [])[colorRef.current]), sizeRef.current)
    }
  }, [p])
  paintRef.current = paint

  // ── loop control ───────────────────────────────────────────────────────────
  const stopLoops = useCallback(() => {
    runningRef.current = false
    if (rafRef.current) cancelAnimationFrame(rafRef.current)
    if (streamRef.current) { streamRef.current.getTracks().forEach((tr) => tr.stop()); streamRef.current = null }
    const v = videoRef.current
    if (v) { try { v.pause() } catch { /* noop */ } }
  }, [])

  const runVideoLoop = useCallback(() => {
    runningRef.current = true
    const video = videoRef.current
    const loop = () => {
      if (!runningRef.current) return
      const lm = getEngine()
      if (video && video.readyState >= 2) {
        if (lm) {
          setRunningMode('VIDEO')
          let ts = performance.now(); if (ts <= lastTsRef.current) ts = lastTsRef.current + 1; lastTsRef.current = ts
          let res = null
          try { res = lm.detectForVideo(video, ts) } catch { /* wrong mode during switch */ }
          paint(res?.faceLandmarks?.[0] || null, res?.facialTransformationMatrixes?.[0] || null, { smooth: true, detActive: true })
        } else {
          paint(null, null, { smooth: true, detActive: false })  // draw frame, model still loading
        }
      }
      rafRef.current = requestAnimationFrame(loop)
    }
    loop()
  }, [getEngine, setRunningMode, paint])

  // ── mode 1: live camera ────────────────────────────────────────────────────
  const startLive = useCallback(async () => {
    try {
      if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) { setErr(t.mirrorCamUnavailable); return }
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' }, audio: false })
      if (!openRef.current) { stream.getTracks().forEach((x) => x.stop()); return }
      streamRef.current = stream
      const video = videoRef.current
      video.srcObject = stream; video.muted = true
      await video.play()
      prepCanvas(video.videoWidth || 640, video.videoHeight || 480)
      sourceRef.current = video
      smoothReset(); setSourceLoaded(true); setErr('')
      runVideoLoop()
    } catch (e) {
      if (e?.name === 'NotAllowedError') setErr(t.mirrorCamBlocked)
      else if (e?.name === 'NotFoundError' || e?.name === 'DevicesNotFoundError' || e?.name === 'OverconstrainedError') setErr(t.mirrorNoCam)
      else setErr(t.mirrorCamUnavailable)
    }
  }, [t, runVideoLoop])

  // ── mode 2: upload photo ───────────────────────────────────────────────────
  const loadPhoto = useCallback((file) => {
    stopLoops()
    if (objUrlRef.current) URL.revokeObjectURL(objUrlRef.current)
    const url = URL.createObjectURL(file); objUrlRef.current = url
    const img = new Image()
    img.onload = async () => {
      const scale = Math.min(1, MAX_IMG / Math.max(img.naturalWidth, img.naturalHeight))
      const W = Math.round(img.naturalWidth * scale), H = Math.round(img.naturalHeight * scale)
      prepCanvas(W, H)
      const canvas = canvasRef.current; if (canvas) canvas.style.transform = 'none'
      sourceRef.current = img; setSourceLoaded(true)
      let l = null, mat = null
      const lm = getEngine()
      if (lm) {
        await setRunningMode('IMAGE')
        try {
          const tmp = document.createElement('canvas'); tmp.width = W; tmp.height = H
          tmp.getContext('2d').drawImage(img, 0, 0, W, H)
          const res = lm.detect(tmp)
          l = res?.faceLandmarks?.[0] || null; mat = res?.facialTransformationMatrixes?.[0] || null
        } catch { /* detection failed */ }
      }
      photoDetRef.current = { l, mat }
      paint(l, mat, { smooth: false, detActive: !!lm })
      setErr(lm && !l ? t.mirrorNoFace : '')
    }
    img.onerror = () => setErr(t.mirrorBadFile)
    img.src = url
  }, [stopLoops, getEngine, setRunningMode, paint, t])

  // ── mode 3: upload video ───────────────────────────────────────────────────
  const loadVideo = useCallback((file) => {
    stopLoops()
    if (objUrlRef.current) URL.revokeObjectURL(objUrlRef.current)
    const url = URL.createObjectURL(file); objUrlRef.current = url
    const video = videoRef.current
    video.srcObject = null; video.src = url; video.muted = true; video.loop = false
    video.style.transform = 'none'
    video.onloadedmetadata = () => {
      prepCanvas(video.videoWidth || 640, video.videoHeight || 480)
      sourceRef.current = video; smoothReset(); setSourceLoaded(true); setErr('')
      runVideoLoop()
      video.play().then(() => setPlaying(true)).catch(() => setPlaying(false))
    }
    video.ontimeupdate = () => setProgress(video.duration ? video.currentTime / video.duration : 0)
    video.onended = () => setPlaying(false)
    video.onerror = () => setErr(t.mirrorBadFile)
  }, [stopLoops, runVideoLoop, t])

  const handleFile = (file, kind) => {
    if (!file) return
    const ok = kind === 'photo' ? file.type.startsWith('image/') : file.type.startsWith('video/')
    if (!ok) { setErr(t.mirrorBadFile); return }
    setErr(''); setPlaying(false); setProgress(0)
    kind === 'photo' ? loadPhoto(file) : loadVideo(file)
  }

  // ── (re)start on mode change / open ─────────────────────────────────────────
  useEffect(() => {
    if (!open) return
    stopLoops()
    sourceRef.current = null; photoDetRef.current = null
    setSourceLoaded(false); setErr(''); setFace(true); setPlaying(false); setProgress(0)
    const canvas = canvasRef.current
    if (canvas) { canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height); canvas.style.transform = mode === 'live' ? 'scaleX(-1)' : 'none' }
    if (mode === 'live') startLive()
    return () => stopLoops()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, mode])

  // Re-render the static photo when size / colour change (video redraws itself).
  useEffect(() => {
    if (mode === 'photo' && photoDetRef.current) {
      const { l, mat } = photoDetRef.current
      paint(l, mat, { smooth: false, detActive: !!getEngine() })
    }
  }, [size, colorIdx, mode, paint, getEngine])

  // Full teardown on close/unmount.
  useEffect(() => {
    if (open) return
    stopLoops()
    if (objUrlRef.current) { URL.revokeObjectURL(objUrlRef.current); objUrlRef.current = null }
    const v = videoRef.current; if (v) { v.srcObject = null; v.removeAttribute('src') }
    if (engineRef.current) { try { engineRef.current.dispose() } catch { /* noop */ } engineRef.current = null }
    modelUrlRef.current = ''
  }, [open, stopLoops])
  useEffect(() => stopLoops, [stopLoops])

  const togglePlay = () => {
    const v = videoRef.current; if (!v) return
    if (v.paused) { v.play().then(() => setPlaying(true)).catch(() => {}) } else { v.pause(); setPlaying(false) }
  }
  const scrub = (frac) => { const v = videoRef.current; if (v && v.duration) { v.currentTime = frac * v.duration; setProgress(frac) } }

  const download = () => {
    const canvas = canvasRef.current; if (!canvas) return
    // Live preview is CSS-mirrored (selfie view); flip the export to match what
    // the user actually saw. Photo/video are shown un-mirrored, so export as-is.
    let src = canvas
    if (mode === 'live') {
      const t = document.createElement('canvas'); t.width = canvas.width; t.height = canvas.height
      const c = t.getContext('2d'); c.translate(t.width, 0); c.scale(-1, 1); c.drawImage(canvas, 0, 0); src = t
    }
    const a = document.createElement('a')
    a.download = 'optizone-tryon.png'
    a.href = src.toDataURL('image/png')
    a.click()
  }

  const bump = (d) => setSize((v) => Math.min(1.4, Math.max(0.8, Math.round((v + d) * 100) / 100)))

  if (!open) return null

  const banner = err
    ? { tone: 'danger', msg: err, retry: false }
    : status === 'loading' ? { tone: 'info', msg: t.mirrorLoading, retry: false }
    : status === 'error' ? { tone: 'danger', msg: t.mirrorInitFail, retry: true }
    : null

  // Portal to <body> — ancestor CSS transforms (.oz-route) would re-anchor a
  // fixed overlay. dir is inherited from <html> so RTL works automatically.
  return createPortal(
    <div style={{ position: 'fixed', inset: 0, zIndex: 1100, background: 'var(--pine-950)', display: 'flex', flexDirection: 'column' }}>
      {/* header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 20px', color: 'var(--cream-100)' }}>
        <span style={{ fontFamily: 'var(--font-display)', letterSpacing: '0.14em', textTransform: 'uppercase', fontSize: 13, color: 'var(--amber-500)' }}>
          {t.tryMirror} · {p.brand} {p.name}
        </span>
        <IconButton variant="ghost" onClick={() => { stopLoops(); onClose() }} aria-label="close" style={{ color: 'var(--cream-100)' }}><Icon name="x" color="var(--cream-100)" /></IconButton>
      </div>

      {/* mode switcher */}
      <div style={{ display: 'flex', gap: 8, justifyContent: 'center', padding: '0 16px 12px', flexWrap: 'wrap' }}>
        {MODES.map((m) => {
          const active = mode === m.key
          return (
            <button key={m.key} onClick={() => setMode(m.key)} aria-pressed={active}
              style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '8px 16px', borderRadius: 'var(--radius-pill)', cursor: 'pointer', fontFamily: 'var(--font-display)', fontSize: 12.5, letterSpacing: '0.08em', textTransform: 'uppercase', border: `1px solid ${active ? 'var(--amber-500)' : 'var(--border-on-dark)'}`, background: active ? 'var(--amber-500)' : 'transparent', color: active ? 'var(--pine-950)' : 'var(--cream-200)' }}>
              <Icon name={m.icon} size={15} color="currentColor" /> {t[m.label]}
            </button>
          )
        })}
      </div>

      {/* banners */}
      {banner && (
        <div role={banner.tone === 'danger' ? 'alert' : 'status'} style={{ margin: '0 16px 10px', padding: '10px 14px', borderRadius: 'var(--radius-md)', fontSize: 13.5, textAlign: 'center', background: banner.tone === 'danger' ? 'rgba(190,60,60,0.16)' : 'rgba(255,255,255,0.08)', color: banner.tone === 'danger' ? '#ffb4a8' : 'var(--cream-100)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10 }}>
          <Icon name={banner.tone === 'danger' ? 'info' : 'camera'} size={15} color="currentColor" /> {banner.msg}
          {banner.retry && <Button variant="outline" size="sm" onClick={retry} style={{ color: 'var(--cream-100)', borderColor: 'var(--cream-100)' }}>{t.mirrorRetry}</Button>}
        </div>
      )}

      {/* stage */}
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', padding: '0 16px', minHeight: 0 }}>
        <div style={{ position: 'relative', width: 'min(92vw, 640px)', maxHeight: '100%', aspectRatio: '4/3', borderRadius: 'var(--radius-lg)', background: '#0e0e0e', border: '1px solid var(--border-on-dark)', overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <video ref={videoRef} playsInline muted style={{ display: 'none' }} />
          <canvas ref={canvasRef} width={640} height={480} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />

          {/* per-mode empty state / hints */}
          {(mode === 'photo' || mode === 'video') && !sourceLoaded && (
            <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 14, color: 'var(--cream-200)' }}>
              <Icon name={mode === 'photo' ? 'user' : 'smartphone'} size={40} color="var(--pine-300)" />
              <Button variant="outline" style={{ color: 'var(--cream-100)', borderColor: 'var(--cream-100)' }}
                onClick={() => (mode === 'photo' ? photoInputRef.current : videoInputRef.current)?.click()}>
                {mode === 'photo' ? t.mirrorChoosePhoto : t.mirrorChooseVideo}
              </Button>
            </div>
          )}
          {mode !== 'photo' && sourceLoaded && status === 'ready' && !hasFace && !err && (
            <div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, padding: '10px 14px', fontSize: 13, color: 'var(--cream-100)', background: 'linear-gradient(transparent, rgba(0,0,0,0.7))', textAlign: 'center' }}>{t.mirrorPosition}</div>
          )}
        </div>
      </div>

      {/* video transport (mode 3) */}
      {mode === 'video' && sourceLoaded && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 24px 0', maxWidth: 680, margin: '0 auto', width: '100%' }}>
          <IconButton variant="ghost" size="sm" onClick={togglePlay} aria-label={playing ? t.mirrorPause : t.mirrorPlay} style={{ color: 'var(--cream-100)', border: '1px solid var(--border-on-dark)' }}>
            <Icon name={playing ? 'chevron-up' : 'arrow-right'} size={15} color="currentColor" />
          </IconButton>
          <input type="range" min="0" max="1" step="0.001" value={progress} onChange={(e) => scrub(Number(e.target.value))} aria-label="scrubber" style={{ flex: 1, accentColor: 'var(--amber-500)' }} />
        </div>
      )}

      {/* controls */}
      <div style={{ padding: '12px 24px 22px', display: 'flex', flexDirection: 'column', gap: 12, alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, color: 'var(--cream-100)' }}>
          <span style={{ fontFamily: 'var(--font-display)', fontSize: 11.5, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--pine-200)' }}>{t.mirrorSize}</span>
          <IconButton variant="ghost" size="sm" onClick={() => bump(-0.05)} aria-label="smaller" style={{ color: 'var(--cream-100)', border: '1px solid var(--border-on-dark)' }}><span style={{ fontSize: 17, lineHeight: 1 }}>−</span></IconButton>
          <input type="range" min="0.8" max="1.4" step="0.05" value={size} onChange={(e) => setSize(Number(e.target.value))} aria-label={t.mirrorSize} style={{ width: 160, accentColor: 'var(--amber-500)' }} />
          <IconButton variant="ghost" size="sm" onClick={() => bump(0.05)} aria-label="larger" style={{ color: 'var(--cream-100)', border: '1px solid var(--border-on-dark)' }}><Icon name="plus" size={15} color="currentColor" /></IconButton>
          <span style={{ fontFamily: 'var(--font-display)', fontSize: 13, minWidth: 44, textAlign: 'center', color: 'var(--amber-500)' }}>{sizePct}</span>
        </div>

        {(p.colors || []).length > 0 && (
          <div style={{ display: 'flex', gap: 10 }}>
            {p.colors.map((c, i) => (
              <button key={i} onClick={() => setColorIdx(i)} aria-label={`color ${i + 1}`} style={{ width: 30, height: 30, borderRadius: 999, background: c, border: `2px solid ${colorIdx === i ? 'var(--amber-500)' : 'transparent'}`, cursor: 'pointer' }} />
            ))}
          </div>
        )}

        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', justifyContent: 'center' }}>
          <Button variant="ghost" onClick={download} style={{ color: 'var(--pine-100)' }} startIcon={<Icon name="share-2" size={16} color="currentColor" />}>{t.mirrorDownload}</Button>
          <Button variant="primary" onClick={() => { stopLoops(); onAddToCart(sizePct); onClose() }} startIcon={<Icon name="shopping-bag" size={17} color="currentColor" />}>
            {t.mirrorAdd} · {sizePct}
          </Button>
        </div>
        <span style={{ fontSize: 11.5, color: 'var(--pine-300)', letterSpacing: '0.04em', textAlign: 'center' }}>{t.mirrorPrivacy}</span>
      </div>

      {/* hidden inputs (also reachable from the empty-state buttons) */}
      <input ref={photoInputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={(e) => { setMode('photo'); handleFile(e.target.files && e.target.files[0], 'photo'); e.target.value = '' }} />
      <input ref={videoInputRef} type="file" accept="video/*" style={{ display: 'none' }} onChange={(e) => { handleFile(e.target.files && e.target.files[0], 'video'); e.target.value = '' }} />
    </div>,
    document.body,
  )
}

// web/components/TryMirror.vue
<script setup lang="ts">
// TryMirror — per-product virtual try-on (live camera / upload photo / upload
// video). All processing in-browser (MediaPipe FaceLandmarker, no key, no
// upload). Overlay fallback chain per colour: 3D model → transparent PNG (incl.
// auto-derived from the product photo) → drawn vector. Vue port of the React
// component; mounted only while open, so mount/unmount == open/close.
import { ShoppingBag, Share2, X, Camera, User, Smartphone, Plus, Info, Play, Pause } from 'lucide-vue-next'
import { resolveTryonAsset } from '~/tryon/config.js'
import { removeBackground } from '~/tryon/bgRemove.js'

const props = withDefaults(defineProps<{
  product: any
  catalog?: any[]
}>(), { catalog: () => [] })
const emit = defineEmits<{ (e: 'close'): void; (e: 'add', size: string, product: any): void }>()

const { L } = useLang()

// GlassesEngine (+ three) is loaded on demand — only when a frame asset exists.
let EnginePromise: Promise<any> | null = null
const loadEngine = () => (EnginePromise ||= import('~/tryon/GlassesEngine.js').then((m: any) => m.GlassesEngine))

// Inline trilingual strings (EN/HE full; AR subset → EN fallback via L()).
const S = {
  tryMirror: { en: 'Try Mirror', he: 'Try Mirror', ar: 'المرآة الافتراضية' },
  modeLive: { en: 'Live', he: 'מצלמה חיה', ar: 'مباشر' },
  modePhoto: { en: 'Upload photo', he: 'העלאת תמונה', ar: 'رفع صورة' },
  modeVideo: { en: 'Upload video', he: 'העלאת וידאו', ar: 'رفع فيديو' },
  choosePhoto: { en: 'Choose a photo', he: 'בחירת תמונה', ar: 'اختر صورة' },
  chooseVideo: { en: 'Choose a video', he: 'בחירת וידאו', ar: 'اختر فيديو' },
  loading: { en: 'Loading face tracking…', he: 'טוען זיהוי פנים…', ar: 'جارٍ تحميل تتبّع الوجه…' },
  noFace: { en: 'No face detected — try a clear, front-facing photo.', he: 'לא זוהו פנים — נסו תמונה ברורה, פנים קדימה.', ar: 'لم يُكتشف وجه — جرّب صورة واضحة من الأمام.' },
  camBlocked: { en: 'Camera permission blocked — you can upload a photo instead.', he: 'הרשאת המצלמה נחסמה — אפשר להעלות תמונה במקום.', ar: 'تم حظر إذن الكاميرا — يمكنك رفع صورة بدلاً من ذلك.' },
  camUnavailable: { en: 'Camera is not available here — upload a photo instead.', he: 'המצלמה אינה זמינה כאן — העלו תמונה במקום.', ar: 'الكاميرا غير متاحة هنا — ارفع صورة بدلاً من ذلك.' },
  noCam: { en: 'No camera found — upload a photo or video instead.', he: 'לא נמצאה מצלמה — העלו תמונה או וידאו במקום.', ar: 'لا كاميرا — ارفع صورة أو فيديو.' },
  badFile: { en: 'That file type isn’t supported — please choose another.', he: 'סוג הקובץ אינו נתמך — בחרו קובץ אחר.', ar: 'نوع الملف غير مدعوم — اختر آخر.' },
  initFail: { en: 'Face tracking couldn’t load — check your connection and try again.', he: 'זיהוי הפנים לא נטען — בדקו את החיבור ונסו שוב.', ar: 'تعذّر تحميل تتبّع الوجه — تحقّق من اتصالك.' },
  position: { en: 'Position your face in the frame', he: 'מקמו את הפנים במסגרת', ar: 'ضع وجهك في الإطار' },
  size: { en: 'Frame size', he: 'גודל מסגרת', ar: 'حجم الإطار' },
  download: { en: 'Download photo', he: 'הורדת תמונה', ar: 'تنزيل الصورة' },
  add: { en: 'Add to Cart', he: 'הוספה לעגלה', ar: 'أضف إلى السلة' },
  retry: { en: 'Retry', he: 'נסו שוב', ar: 'أعد المحاولة' },
  privacy: { en: 'Everything runs on your device — no image ever leaves your browser.', he: 'הכול רץ על המכשיר שלכם — אף תמונה לא עוזבת את הדפדפן.', ar: 'كل شيء يعمل على جهازك — لا تغادر أي صورة متصفحك.' },
}

const BASE_MULT = 2.15
const EMA_ALPHA = 0.5
const MAX_IMG = 1600

const { status, load: loadLandmarker, get: getLm, setRunningMode, retry: retryLm } = useFaceLandmarker()

// reactive UI state
const active = ref<any>(props.product || {})
const mode = ref<'live' | 'photo' | 'video'>('live')
const size = ref(1)
const colorIdx = ref(0)
const err = ref('')
const hasFace = ref(true)
const sourceLoaded = ref(false)
const playing = ref(false)
const progress = ref(0)
const sizePct = computed(() => `${Math.round(size.value * 100)}%`)

// template refs
const dialogRef = ref<HTMLElement | null>(null)
const videoRef = ref<HTMLVideoElement | null>(null)
const canvasRef = ref<HTMLCanvasElement | null>(null)
const photoInputRef = ref<HTMLInputElement | null>(null)
const videoInputRef = ref<HTMLInputElement | null>(null)

// non-reactive engine/loop state (per-instance)
let frameImg: HTMLImageElement | null = null
let engine: any = null
let modelUrlCur = ''
let pngUrlCur = ''
let contentUrlCur = ''
let meta: any = {}
let source: HTMLVideoElement | HTMLImageElement | null = null
let photoDet: { l: any; mat: any } | null = null
let smooth: any = {}
let raf = 0
let running = false
let stream: MediaStream | null = null
let objUrl: string | null = null
let lastTs = 0
let assetToken = 0

const setFace = (v: boolean) => { if (hasFace.value !== v) hasFace.value = v }
const smoothReset = () => { smooth = {} }
const prepCanvas = (w: number, h: number) => { const c = canvasRef.value; if (c) { c.width = w; c.height = h } }

// ── head pose from MediaPipe transform matrix ──────────────────────────────
function headAngles(mat: any) {
  if (!mat) return { yaw: 0, pitch: 0 }
  const m = mat.data || mat
  const r00 = m[0], r10 = m[1], r20 = m[2], r21 = m[6], r22 = m[10]
  const sy = Math.hypot(r00, r10)
  return { pitch: Math.atan2(r21, r22), yaw: Math.atan2(-r20, sy) }
}
const ema = (prev: any, cur: any, a: number) => (prev == null ? cur : { x: prev.x + a * (cur.x - prev.x), y: prev.y + a * (cur.y - prev.y) })

// ── vector fallback ────────────────────────────────────────────────────────
function vectorStyle(product: any, color: string) {
  const shape = String(product?.shape || '').toLowerCase()
  if (shape.includes('aviator')) return { stroke: color || '#b8862f', lw: 0.05, rx: 0.30, ry: 0.25, tint: 'rgba(120,90,30,0.16)' }
  if (shape.includes('round') || shape.includes('oval')) return { stroke: color || '#2b2b2b', lw: 0.055, rx: 0.26, ry: 0.26, tint: 'rgba(20,20,25,0.10)' }
  return { stroke: color || '#141414', lw: 0.075, rx: 0.31, ry: 0.23, tint: null as string | null }
}
function drawVector(ctx: any, lm: any, W: number, H: number, st: any, scale: number) {
  const P = (i: number) => ({ x: lm[i].x * W, y: lm[i].y * H })
  if (!lm[33] || !lm[263]) return
  const rO = P(33), lO = P(263), rIn = P(133) || rO, lIn = P(362) || lO, rEar = P(234) || rO, lEar = P(454) || lO
  const rEye = { x: (rO.x + rIn.x) / 2, y: (rO.y + rIn.y) / 2 }
  const lEye = { x: (lO.x + lIn.x) / 2, y: (lO.y + lIn.y) / 2 }
  const span = Math.hypot(lO.x - rO.x, lO.y - rO.y)
  const ang = Math.atan2(lO.y - rO.y, lO.x - rO.x)
  const ux = Math.cos(ang), uy = Math.sin(ang)
  const rx = span * st.rx * scale, ry = span * st.ry * scale, lw = Math.max(1.5, span * st.lw * scale)
  ctx.save(); ctx.lineJoin = 'round'; ctx.lineCap = 'round'; ctx.strokeStyle = st.stroke; ctx.lineWidth = lw
  for (const c of [rEye, lEye]) { ctx.beginPath(); ctx.ellipse(c.x, c.y, rx, ry, ang, 0, Math.PI * 2); if (st.tint) { ctx.fillStyle = st.tint; ctx.fill() } ctx.stroke() }
  ctx.beginPath(); ctx.moveTo(rEye.x + ux * rx, rEye.y + uy * rx); ctx.lineTo(lEye.x - ux * rx, lEye.y - uy * rx); ctx.stroke()
  ctx.beginPath(); ctx.moveTo(rEye.x - ux * rx, rEye.y - uy * rx); ctx.lineTo(rEar.x, rEar.y); ctx.stroke()
  ctx.beginPath(); ctx.moveTo(lEye.x + ux * rx, lEye.y + uy * rx); ctx.lineTo(lEar.x, lEar.y); ctx.stroke()
  ctx.restore()
}
function drawPng(ctx: any, img: any, p33: any, p263: any, p168: any, mat: any, scale: number) {
  const dx = p263.x - p33.x, dy = p263.y - p33.y
  const eyeDist = Math.hypot(dx, dy)
  const roll = Math.atan2(dy, dx)
  const { yaw, pitch } = headAngles(mat)
  const width = eyeDist * BASE_MULT * scale
  const height = width * (img.naturalHeight / img.naturalWidth || 0.4)
  const squeeze = Math.max(0.45, Math.cos(yaw))
  const yawShift = Math.sin(yaw) * eyeDist * 0.15
  const pitchShift = Math.sin(pitch) * eyeDist * 0.12
  ctx.save()
  ctx.translate(p168.x + yawShift, p168.y + pitchShift)
  ctx.rotate(roll)
  ctx.scale(squeeze, 1)
  ctx.drawImage(img, -width / 2, -height * 0.5, width, height)
  ctx.restore()
}

// ── auto-derive frame from product photo (background removed) ───────────────
const autoCache = new Map<string, string>()
async function autoDeriveFrame(url: string) {
  if (!url) return ''
  if (autoCache.has(url)) return autoCache.get(url)!
  let out = ''
  try { const r: any = await removeBackground(url, { auto: true }); if (r && r.coverage > 0.015 && r.coverage < 0.75) out = r.dataUrl } catch { /* → vector */ }
  autoCache.set(url, out)
  return out
}

// ── shared paint ───────────────────────────────────────────────────────────
function paint(landmarks: any, mat: any, opts: { smooth: boolean; detActive: boolean }) {
  const canvas = canvasRef.value
  if (!canvas) return
  const ctx = canvas.getContext('2d')!
  const W = canvas.width, H = canvas.height
  ctx.clearRect(0, 0, W, H)
  if (source) { try { ctx.drawImage(source as any, 0, 0, W, H) } catch { /* not ready */ } }
  if (opts.detActive) setFace(!!landmarks)
  const contentReady = engine && contentUrlCur && engine.hasContent(contentUrlCur)
  if (!landmarks) {
    if (contentReady) { engine.resize(W, H); engine.update(null, meta, size.value, false); try { ctx.drawImage(engine.render(), 0, 0, W, H) } catch { /* gl */ } }
    return
  }
  if (contentReady && landmarks[33] && landmarks[263]) {
    engine.resize(W, H)
    engine.update(landmarks, meta, size.value, false)
    try { ctx.drawImage(engine.render(), 0, 0, W, H) } catch { /* gl */ }
  } else if (frameImg && landmarks[33] && landmarks[263] && landmarks[168]) {
    let a = { x: landmarks[33].x * W, y: landmarks[33].y * H }
    let b = { x: landmarks[263].x * W, y: landmarks[263].y * H }
    let n = { x: landmarks[168].x * W, y: landmarks[168].y * H }
    if (opts.smooth) { a = smooth.a = ema(smooth.a, a, EMA_ALPHA); b = smooth.b = ema(smooth.b, b, EMA_ALPHA); n = smooth.n = ema(smooth.n, n, EMA_ALPHA) }
    drawPng(ctx, frameImg, a, b, n, mat, size.value)
  } else if (!pngUrlCur && !modelUrlCur) {
    drawVector(ctx, landmarks, W, H, vectorStyle(active.value, (active.value.colors || [])[colorIdx.value]), size.value)
  }
}
function repaintPhoto() {
  if (photoDet && source) paint(photoDet.l, photoDet.mat, { smooth: false, detActive: true })
}

// ── asset load (fallback chain) ─────────────────────────────────────────────
async function loadAssets() {
  const p = active.value
  const colorHex = (p.colors || [])[colorIdx.value]
  const { model: modelUrl, png: resolvedPng, meta: m } = resolveTryonAsset(p, colorHex)
  const productImg = p.image || ''
  const token = ++assetToken
  meta = m
  contentUrlCur = ''
  frameImg = null
  const giveUp = () => { if (token === assetToken) { contentUrlCur = ''; repaintPhoto() } }
  const ok = (url: string) => { if (token === assetToken) { contentUrlCur = url; repaintPhoto() } }

  let pngUrl = resolvedPng
  if (!modelUrl && !pngUrl && productImg) pngUrl = await autoDeriveFrame(productImg)
  if (token !== assetToken) return
  pngUrlCur = pngUrl
  modelUrlCur = modelUrl
  if (pngUrl) {
    const img = new Image(); img.crossOrigin = 'anonymous'
    img.onload = () => { if (token === assetToken) { frameImg = img; repaintPhoto() } }
    img.onerror = () => { if (token === assetToken && frameImg === img) frameImg = null }
    img.src = pngUrl
  }
  const contentUrl = modelUrl || pngUrl
  if (!contentUrl) { repaintPhoto(); return }
  let GlassesEngine: any
  try { GlassesEngine = await loadEngine() } catch (e: any) { console.warn('[tryon] engine load failed:', e?.message || e); giveUp(); return }
  if (token !== assetToken) return
  if (!engine) { try { engine = new GlassesEngine(640, 480) } catch (e: any) { console.warn('[tryon] WebGL unavailable:', e?.message || e); giveUp(); return } }
  const tryPlane = () => (pngUrl ? engine.setPlane(pngUrl).then((y: boolean) => (y ? ok(pngUrl) : giveUp())) : giveUp())
  if (modelUrl) await engine.setModel(modelUrl).then((y: boolean) => (y ? ok(modelUrl) : tryPlane()))
  else await tryPlane()
}

// ── loop control ─────────────────────────────────────────────────────────
function stopLoops() {
  running = false
  if (raf) cancelAnimationFrame(raf)
  if (stream) { stream.getTracks().forEach((tr) => tr.stop()); stream = null }
  const v = videoRef.value
  if (v) { try { v.pause() } catch { /* noop */ } }
}
function runVideoLoop() {
  running = true
  const video = videoRef.value!
  const loop = () => {
    if (!running) return
    const lm = getLm()
    if (video && video.readyState >= 2) {
      if (lm) {
        setRunningMode('VIDEO')
        let ts = performance.now(); if (ts <= lastTs) ts = lastTs + 1; lastTs = ts
        let res: any = null
        try { res = lm.detectForVideo(video, ts) } catch { /* mode switching */ }
        paint(res?.faceLandmarks?.[0] || null, res?.facialTransformationMatrixes?.[0] || null, { smooth: true, detActive: true })
      } else {
        paint(null, null, { smooth: true, detActive: false })
      }
    }
    raf = requestAnimationFrame(loop)
  }
  loop()
}

// ── mode 1: live camera ──────────────────────────────────────────────────
async function startLive() {
  try {
    if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) { err.value = L(S.camUnavailable); return }
    const s = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' }, audio: false })
    stream = s
    const video = videoRef.value!
    video.srcObject = s; video.muted = true
    await video.play()
    prepCanvas(video.videoWidth || 640, video.videoHeight || 480)
    source = video
    smoothReset(); sourceLoaded.value = true; err.value = ''
    runVideoLoop()
  } catch (e: any) {
    if (e?.name === 'NotAllowedError') err.value = L(S.camBlocked)
    else if (e?.name === 'NotFoundError' || e?.name === 'DevicesNotFoundError' || e?.name === 'OverconstrainedError') err.value = L(S.noCam)
    else err.value = L(S.camUnavailable)
  }
}

// ── mode 2: upload photo ───────────────────────────────────────────────────
function loadPhoto(file: File) {
  stopLoops()
  if (objUrl) URL.revokeObjectURL(objUrl)
  const url = URL.createObjectURL(file); objUrl = url
  const img = new Image()
  img.onload = async () => {
    const scale = Math.min(1, MAX_IMG / Math.max(img.naturalWidth, img.naturalHeight))
    const W = Math.round(img.naturalWidth * scale), H = Math.round(img.naturalHeight * scale)
    prepCanvas(W, H)
    const canvas = canvasRef.value; if (canvas) canvas.style.transform = 'none'
    source = img; sourceLoaded.value = true
    let l: any = null, mat: any = null
    const lm = getLm()
    if (lm) {
      await setRunningMode('IMAGE')
      try {
        const tmp = document.createElement('canvas'); tmp.width = W; tmp.height = H
        tmp.getContext('2d')!.drawImage(img, 0, 0, W, H)
        const res = lm.detect(tmp)
        l = res?.faceLandmarks?.[0] || null; mat = res?.facialTransformationMatrixes?.[0] || null
      } catch { /* detection failed */ }
    }
    photoDet = { l, mat }
    paint(l, mat, { smooth: false, detActive: !!lm })
    err.value = lm && !l ? L(S.noFace) : ''
  }
  img.onerror = () => { err.value = L(S.badFile) }
  img.src = url
}

// ── mode 3: upload video ───────────────────────────────────────────────────
function loadVideo(file: File) {
  stopLoops()
  if (objUrl) URL.revokeObjectURL(objUrl)
  const url = URL.createObjectURL(file); objUrl = url
  const video = videoRef.value!
  video.srcObject = null; video.src = url; video.muted = true; video.loop = false
  video.style.transform = 'none'
  video.onloadedmetadata = () => {
    prepCanvas(video.videoWidth || 640, video.videoHeight || 480)
    source = video; smoothReset(); sourceLoaded.value = true; err.value = ''
    runVideoLoop()
    video.play().then(() => (playing.value = true)).catch(() => (playing.value = false))
  }
  video.ontimeupdate = () => { progress.value = video.duration ? video.currentTime / video.duration : 0 }
  video.onended = () => { playing.value = false }
  video.onerror = () => { err.value = L(S.badFile) }
}

function handleFile(file: File | null | undefined, kind: 'photo' | 'video') {
  if (!file) return
  const okType = kind === 'photo' ? file.type.startsWith('image/') : file.type.startsWith('video/')
  if (!okType) { err.value = L(S.badFile); return }
  err.value = ''; playing.value = false; progress.value = 0
  kind === 'photo' ? loadPhoto(file) : loadVideo(file)
}

// ── mode switch ────────────────────────────────────────────────────────────
function applyMode() {
  stopLoops()
  source = null; photoDet = null
  sourceLoaded.value = false; err.value = ''; setFace(true); playing.value = false; progress.value = 0
  const canvas = canvasRef.value
  if (canvas) { canvas.getContext('2d')!.clearRect(0, 0, canvas.width, canvas.height); canvas.style.transform = mode.value === 'live' ? 'scaleX(-1)' : 'none' }
  if (mode.value === 'live') startLive()
}
watch(mode, applyMode)
watch([colorIdx, active], loadAssets, { deep: true })
watch([size, colorIdx], () => { if (mode.value === 'photo' && photoDet) paint(photoDet.l, photoDet.mat, { smooth: false, detActive: !!getLm() }) })

// carousel: switch tried-on frame in place
function switchProduct(prod: any) { active.value = prod; colorIdx.value = 0 }

// transport
function togglePlay() {
  const v = videoRef.value; if (!v) return
  if (v.paused) { v.play().then(() => (playing.value = true)).catch(() => {}) } else { v.pause(); playing.value = false }
}
function scrub(frac: number) { const v = videoRef.value; if (v && v.duration) { v.currentTime = frac * v.duration; progress.value = frac } }

function download() {
  const canvas = canvasRef.value; if (!canvas) return
  let src: HTMLCanvasElement = canvas
  if (mode.value === 'live') {
    const tc = document.createElement('canvas'); tc.width = canvas.width; tc.height = canvas.height
    const c = tc.getContext('2d')!; c.translate(tc.width, 0); c.scale(-1, 1); c.drawImage(canvas, 0, 0); src = tc
  }
  const a = document.createElement('a')
  a.download = 'optizone-tryon.png'
  a.href = src.toDataURL('image/png')
  a.click()
}
const bump = (d: number) => { size.value = Math.min(1.4, Math.max(0.8, Math.round((size.value + d) * 100) / 100)) }

const banner = computed(() => {
  if (err.value) return { tone: 'danger', msg: err.value, retry: false }
  if (status.value === 'loading') return { tone: 'info', msg: L(S.loading), retry: false }
  if (status.value === 'error') return { tone: 'danger', msg: L(S.initFail), retry: true }
  return null
})

const MODES = [
  { key: 'live', Icon: Camera, label: S.modeLive },
  { key: 'photo', Icon: User, label: S.modePhoto },
  { key: 'video', Icon: Smartphone, label: S.modeVideo },
] as const

function close() { stopLoops(); emit('close') }
function addToCart() { stopLoops(); emit('add', sizePct.value, active.value); emit('close') }

let onKey: (e: KeyboardEvent) => void
onMounted(() => {
  loadLandmarker()
  loadAssets()
  applyMode()
  dialogRef.value?.focus()
  onKey = (e) => { if (e.key === 'Escape') close() }
  window.addEventListener('keydown', onKey)
})
onUnmounted(() => {
  stopLoops()
  if (onKey) window.removeEventListener('keydown', onKey)
  if (objUrl) { URL.revokeObjectURL(objUrl); objUrl = null }
  const v = videoRef.value; if (v) { v.srcObject = null; v.removeAttribute('src') }
  if (engine) { try { engine.dispose() } catch { /* noop */ } engine = null }
})
</script>

<template>
  <Teleport to="body">
    <div ref="dialogRef" tabindex="-1" role="dialog" aria-modal="true" :aria-label="`${L(S.tryMirror)} · ${active.brand} ${L(active.name) || active.name}`"
      class="fixed inset-0 z-[1100] flex flex-col bg-pine-950 text-cream-100 outline-none">
      <!-- header -->
      <div class="flex items-center justify-between px-5 py-3.5">
        <span class="font-display text-[13px] uppercase tracking-[0.14em] text-amber-500">{{ L(S.tryMirror) }} · {{ active.brand }} {{ L(active.name) || active.name }}</span>
        <button @click="close" aria-label="close" class="rounded-full p-2 text-cream-100 hover:bg-white/10"><X :size="20" /></button>
      </div>

      <!-- mode switcher -->
      <div class="flex flex-wrap justify-center gap-2 px-4 pb-3">
        <button v-for="m in MODES" :key="m.key" @click="mode = m.key as any" :aria-pressed="mode === m.key"
          class="inline-flex items-center gap-2 rounded-pill border px-4 py-2 font-display text-[12.5px] uppercase tracking-[0.08em] transition-colors"
          :class="mode === m.key ? 'border-amber-500 bg-amber-500 text-pine-950' : 'border-white/25 text-cream-200 hover:border-white/50'">
          <component :is="m.Icon" :size="15" /> {{ L(m.label) }}
        </button>
      </div>

      <!-- banner -->
      <div v-if="banner" :role="banner.tone === 'danger' ? 'alert' : 'status'" class="mx-4 mb-2.5 flex items-center justify-center gap-2.5 rounded-md px-3.5 py-2.5 text-center text-[13.5px]"
        :class="banner.tone === 'danger' ? 'bg-red-500/15 text-red-200' : 'bg-white/10 text-cream-100'">
        <Info :size="15" /> {{ banner.msg }}
        <button v-if="banner.retry" @click="retryLm" class="rounded-sm border border-cream-100 px-3 py-1 text-xs">{{ L(S.retry) }}</button>
      </div>

      <!-- stage -->
      <div class="relative flex min-h-0 flex-1 items-center justify-center px-4">
        <div class="relative flex items-center justify-center overflow-hidden rounded-lg border border-white/20 bg-[#0e0e0e]" style="width:min(92vw,640px); max-height:100%; aspect-ratio:4/3">
          <video ref="videoRef" playsinline muted class="hidden" />
          <canvas ref="canvasRef" width="640" height="480" class="block h-full w-full object-cover" />
          <div v-if="(mode === 'photo' || mode === 'video') && !sourceLoaded" class="absolute inset-0 flex flex-col items-center justify-center gap-3.5 text-cream-200">
            <component :is="mode === 'photo' ? User : Smartphone" :size="40" class="text-pine-300" />
            <button @click="(mode === 'photo' ? photoInputRef : videoInputRef)?.click()" class="rounded-sm border border-cream-100 px-5 py-2.5 text-sm">
              {{ mode === 'photo' ? L(S.choosePhoto) : L(S.chooseVideo) }}
            </button>
          </div>
          <div v-if="mode !== 'photo' && sourceLoaded && status === 'ready' && !hasFace && !err" class="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-3.5 py-2.5 text-center text-[13px] text-cream-100">{{ L(S.position) }}</div>
        </div>
      </div>

      <!-- video transport -->
      <div v-if="mode === 'video' && sourceLoaded" class="mx-auto flex w-full max-w-[680px] items-center gap-3 px-6 pt-2.5">
        <button @click="togglePlay" :aria-label="playing ? 'pause' : 'play'" class="rounded-sm border border-white/20 p-2 text-cream-100"><component :is="playing ? Pause : Play" :size="15" /></button>
        <input type="range" min="0" max="1" step="0.001" :value="progress" @input="scrub(Number(($event.target as HTMLInputElement).value))" aria-label="scrubber" class="flex-1 accent-amber-500" />
      </div>

      <!-- product carousel -->
      <div v-if="catalog.length > 1" role="listbox" :aria-label="L(S.tryMirror)" class="flex gap-2.5 overflow-x-auto px-5 pb-2.5 pt-1.5" style="scroll-snap-type:x mandatory">
        <button v-for="prod in catalog" :key="prod.id" role="option" :aria-selected="prod.id === active.id" @click="switchProduct(prod)"
          class="w-28 flex-none rounded-md border p-2 text-center text-cream-100" style="scroll-snap-align:center"
          :class="prod.id === active.id ? 'border-amber-500 bg-amber-500/15' : 'border-white/20'">
          <span class="mb-1.5 flex h-11 items-center justify-center overflow-hidden rounded bg-white/5">
            <img v-if="prod.image" :src="prod.image" alt="" class="max-h-full max-w-full object-contain" />
          </span>
          <span class="block truncate text-[9.5px] uppercase tracking-wide text-pine-200">{{ prod.brand }}</span>
          <span class="block truncate text-[11px] leading-tight">{{ L(prod.name) || prod.name }}</span>
          <span class="block text-[12.5px] font-bold text-amber-500">₪{{ prod.amount }}</span>
        </button>
      </div>

      <!-- controls -->
      <div class="flex flex-col items-center gap-3 px-6 pb-6 pt-3">
        <div class="flex items-center gap-3 text-cream-100">
          <span class="font-display text-[11.5px] uppercase tracking-[0.12em] text-pine-200">{{ L(S.size) }}</span>
          <button @click="bump(-0.05)" aria-label="smaller" class="rounded-sm border border-white/20 px-2.5 py-1 text-lg leading-none">−</button>
          <input type="range" min="0.8" max="1.4" step="0.05" v-model.number="size" :aria-label="L(S.size)" class="w-40 accent-amber-500" />
          <button @click="bump(0.05)" aria-label="larger" class="rounded-sm border border-white/20 p-1.5"><Plus :size="15" /></button>
          <span class="min-w-[44px] text-center font-display text-sm text-amber-500">{{ sizePct }}</span>
        </div>
        <div v-if="(active.colors || []).length" class="flex gap-2.5">
          <button v-for="(c, i) in active.colors" :key="i" @click="colorIdx = i" :aria-label="`color ${i + 1}`"
            class="h-[30px] w-[30px] rounded-full border-2" :style="{ background: c }" :class="colorIdx === i ? 'border-amber-500' : 'border-transparent'" />
        </div>
        <div class="flex flex-wrap justify-center gap-2.5">
          <button @click="download" class="inline-flex items-center gap-2 rounded-sm px-4 py-2.5 text-pine-100 hover:bg-white/10"><Share2 :size="16" /> {{ L(S.download) }}</button>
          <button @click="addToCart" class="inline-flex items-center gap-2 rounded-sm bg-amber-500 px-5 py-2.5 font-display text-sm text-pine-950 hover:brightness-105"><ShoppingBag :size="17" /> {{ L(S.add) }} · {{ sizePct }}</button>
        </div>
        <span class="text-center text-[11.5px] tracking-[0.04em] text-pine-300">{{ L(S.privacy) }}</span>
      </div>

      <input ref="photoInputRef" type="file" accept="image/*" class="hidden" @change="mode = 'photo'; handleFile(($event.target as HTMLInputElement).files?.[0], 'photo'); ($event.target as HTMLInputElement).value = ''" />
      <input ref="videoInputRef" type="file" accept="video/*" class="hidden" @change="handleFile(($event.target as HTMLInputElement).files?.[0], 'video'); ($event.target as HTMLInputElement).value = ''" />
    </div>
  </Teleport>
</template>
