// project/storefront/Booking.jsx
// OPTIZONE storefront — Appointment booking.
const { Button, Icon, Tag, Select, Input, DiamondRule, Card } = window.OPTIZONEDesignSystem_ded4a5;

function Field({ label, children }) {
  return (
    <div>
      <div style={{ fontFamily: 'var(--font-display)', fontSize: 12, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 12 }}>{label}</div>
      {children}
    </div>
  );
}

function Booking({ go }) {
  const D = window.OZ_DATA;
  const [service, setService] = React.useState(D.bookingServices[0]);
  const [branch, setBranch] = React.useState(D.branches[0]);
  const [slot, setSlot] = React.useState('10:30');
  const [done, setDone] = React.useState(false);
  React.useEffect(() => { window.lucide && window.lucide.createIcons(); });

  const days = ['Sun 6', 'Mon 7', 'Tue 8', 'Wed 9', 'Thu 10'];
  const [day, setDay] = React.useState('Mon 7');

  if (done) {
    return (
      <div style={{ maxWidth: 620, margin: '60px auto 100px', padding: '0 28px', textAlign: 'center' }}>
        <span style={{ width: 64, height: 64, borderRadius: 999, background: 'var(--pine-50)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto' }}>
          <Icon name="check" size={30} color="var(--pine-700)" />
        </span>
        <h1 style={{ fontFamily: 'var(--font-display)', fontWeight: 500, fontSize: 34, color: 'var(--text-strong)', margin: '20px 0 8px' }}>You're booked</h1>
        <p style={{ fontSize: 16, color: 'var(--text-body)', lineHeight: 1.6 }}>{service} · {branch}<br />{day} · {slot}</p>
        <div style={{ margin: '20px auto', maxWidth: 260 }}><DiamondRule /></div>
        <p style={{ fontSize: 14, color: 'var(--text-muted)' }}>A confirmation and reminders will be sent via WhatsApp & email. Reschedule anytime from the link.</p>
        <div style={{ marginTop: 26, display: 'flex', gap: 12, justifyContent: 'center' }}>
          <Button variant="outline" onClick={() => setDone(false)}>Edit booking</Button>
          <Button variant="primary" onClick={() => go('home')}>Back to home</Button>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div style={{ background: 'var(--pine-700)', color: 'var(--cream-100)' }}>
        <div style={{ maxWidth: 'var(--container-max)', margin: '0 auto', padding: '46px 28px' }}>
          <span style={{ fontFamily: 'var(--font-display)', fontSize: 13, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--amber-500)' }}>Book an appointment</span>
          <h1 style={{ fontFamily: 'var(--font-display)', fontWeight: 500, fontSize: 40, color: 'var(--cream-100)', margin: '10px 0 0' }}>Eye care, on your schedule</h1>
        </div>
      </div>

      <div style={{ maxWidth: 900, margin: '0 auto', padding: '36px 28px 80px', display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: 40, alignItems: 'start' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}>
          <Field label="1 · Service">
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
              {D.bookingServices.map((s) => <Tag key={s} selected={service === s} onClick={() => setService(s)}>{s}</Tag>)}
            </div>
          </Field>
          <Field label="2 · Branch">
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {D.branches.map((b) => (
                <button key={b} onClick={() => setBranch(b)} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '14px 16px', textAlign: 'start', borderRadius: 'var(--radius-md)', border: `1.5px solid ${branch === b ? 'var(--pine-700)' : 'var(--border-hair)'}`, background: branch === b ? 'var(--pine-50)' : 'var(--white)', cursor: 'pointer' }}>
                  <Icon name="map-pin" size={18} color="var(--pine-700)" />
                  <span style={{ fontSize: 15, color: 'var(--text-strong)' }}>{b}</span>
                </button>
              ))}
            </div>
          </Field>
          <Field label="3 · Date">
            <div style={{ display: 'flex', gap: 10 }}>
              {days.map((d) => (
                <button key={d} onClick={() => setDay(d)} style={{ flex: 1, padding: '12px 0', borderRadius: 'var(--radius-sm)', border: `1.5px solid ${day === d ? 'var(--amber-600)' : 'var(--border-hair)'}`, background: day === d ? 'var(--amber-50)' : 'var(--white)', cursor: 'pointer', fontFamily: 'var(--font-display)', fontSize: 13, letterSpacing: '0.04em', color: 'var(--text-strong)' }}>{d}</button>
              ))}
            </div>
          </Field>
          <Field label="4 · Time">
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 10 }}>
              {D.slots.map((t) => (
                <button key={t} onClick={() => setSlot(t)} style={{ padding: '12px 0', borderRadius: 'var(--radius-sm)', border: `1.5px solid ${slot === t ? 'var(--pine-700)' : 'var(--border-hair)'}`, background: slot === t ? 'var(--pine-700)' : 'var(--white)', color: slot === t ? 'var(--cream-100)' : 'var(--text-body)', cursor: 'pointer', fontFamily: 'var(--font-body)', fontSize: 14, fontWeight: 600 }}>{t}</button>
              ))}
            </div>
          </Field>
        </div>

        {/* summary */}
        <Card padding="lg" style={{ position: 'sticky', top: 96 }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 14, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--text-strong)', marginBottom: 16 }}>Your appointment</div>
          {[['Service', service], ['Branch', branch], ['Date', day], ['Time', slot]].map(([k, v]) => (
            <div key={k} style={{ display: 'flex', justifyContent: 'space-between', gap: 12, padding: '10px 0', borderBottom: '1px solid var(--border-hair)' }}>
              <span style={{ fontSize: 13, color: 'var(--text-muted)' }}>{k}</span>
              <span style={{ fontSize: 14, color: 'var(--text-strong)', fontWeight: 600, textAlign: 'end' }}>{v}</span>
            </div>
          ))}
          <div style={{ marginTop: 18, display: 'flex', flexDirection: 'column', gap: 12 }}>
            <Input placeholder="Full name" />
            <Input placeholder="Phone · 05X-XXX-XXXX" />
          </div>
          <div style={{ marginTop: 16 }}><Button variant="primary" block size="lg" onClick={() => setDone(true)}>Confirm booking</Button></div>
          <p style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 12, textAlign: 'center' }}>No payment needed. Free reschedule & cancellation.</p>
        </Card>
      </div>
    </div>
  );
}

Object.assign(window, { Booking });

// web/pages/booking.vue
<script setup lang="ts">
import { Check, Calendar } from 'lucide-vue-next'
const { L, lang } = useLang()
const { content } = useContent()
const { user } = useAuth()

const T = {
  eyebrow: { en: 'Book an appointment', he: 'קביעת תור', ar: 'احجز موعدًا' },
  h1: { en: 'Eye care, on your schedule', he: 'טיפול בעיניים, בזמן שנוח לכם', ar: 'رعاية العين وفق جدولك' },
  s1: { en: 'Service', he: 'שירות', ar: 'الخدمة' },
  s2: { en: 'Branch', he: 'סניף', ar: 'الفرع' },
  s3: { en: 'Date', he: 'תאריך', ar: 'التاريخ' },
  s4: { en: 'Time', he: 'שעה', ar: 'الوقت' },
  fullName: { en: 'Full name', he: 'שם מלא', ar: 'الاسم الكامل' },
  phone: { en: 'Phone · 05X-XXX-XXXX', he: 'טלפון · 05X-XXX-XXXX', ar: 'الهاتف · 05X-XXX-XXXX' },
  confirm: { en: 'Confirm booking', he: 'אישור התור', ar: 'تأكيد الحجز' },
  noPay: { en: 'No payment needed. Free reschedule & cancellation.', he: 'ללא תשלום. שינוי וביטול ללא עלות.', ar: 'لا حاجة للدفع. إعادة جدولة وإلغاء مجانًا.' },
  doneH1: { en: "You're booked", he: 'התור נקבע', ar: 'تم الحجز' },
  doneNote: { en: 'A confirmation and reminders will be sent via WhatsApp & email.', he: 'אישור ותזכורות יישלחו בוואטסאפ ובאימייל.', ar: 'سيُرسل تأكيد وتذكيرات عبر واتساب والبريد.' },
  backHome: { en: 'Back to home', he: 'חזרה לדף הבית', ar: 'العودة للرئيسية' },
  summary: { en: 'Your appointment', he: 'התור שלך', ar: 'موعدك' },
  err: { en: 'Please complete all fields.', he: 'נא למלא את כל השדות.', ar: 'يرجى إكمال جميع الحقول.' },
}

const services = computed(() => content.value?.bookingServices || [])
const branches = computed(() => content.value?.stores || [])
const slots = computed(() => content.value?.slots || ['09:00', '10:30', '12:00', '13:30', '15:00', '16:30', '18:00'])
// Next five upcoming week days.
const days = computed(() => {
  const names = { en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], he: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳'], ar: ['أحد', 'إثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'سبت'] }
  const arr: string[] = []
  const base = new Date()
  for (let i = 0; i < 5; i++) { const d = new Date(base); d.setDate(base.getDate() + i); arr.push(`${(names as any)[lang.value][d.getDay()]} ${d.getDate()}`) }
  return arr
})

const form = reactive({ service: '', branch: '', day: '', slot: '', name: user.value?.name || '', phone: user.value?.phone || '' })
watch(user, (u) => { if (u) { form.name = form.name || u.name; form.phone = form.phone || u.phone || '' } })

const err = ref('')
const busy = ref(false)
const done = ref(false)
const bookingId = ref('')
const { authHeaders } = useAuth()

const submit = async () => {
  if (busy.value) return
  if (!form.service || !form.branch || !form.day || !form.slot || form.name.trim().length < 2 || form.phone.replace(/\D/g, '').length < 7) { err.value = L(T.err); return }
  busy.value = true; err.value = ''
  try {
    const r: any = await $fetch('/api/bookings', {
      method: 'POST', headers: authHeaders(),
      body: { service: form.service, branch: form.branch, day: form.day, slot: form.slot, name: form.name, phone: form.phone },
    })
    bookingId.value = r?.id || ''
    done.value = true
  } catch (e: any) { err.value = e?.data?.error || 'Something went wrong' }
  finally { busy.value = false }
}

useHead({ title: 'Book an Exam — OPTIZONE' })
</script>

<template>
  <div>
    <!-- header band -->
    <div class="bg-pine-700 text-cream-100">
      <div class="mx-auto max-w-container px-7 py-12">
        <span class="font-display text-[13px] uppercase tracking-[0.18em] text-amber-500">{{ L(T.eyebrow) }}</span>
        <h1 class="mt-2 font-display text-4xl font-medium">{{ L(T.h1) }}</h1>
      </div>
    </div>

    <!-- DONE -->
    <div v-if="done" class="mx-auto max-w-lg px-7 py-16 text-center">
      <span class="mx-auto inline-flex h-20 w-20 items-center justify-center rounded-full bg-pine-50"><Check :size="36" class="text-pine-700" /></span>
      <h2 class="mb-1.5 mt-6 font-display text-3xl font-medium text-ink-900">{{ L(T.doneH1) }}</h2>
      <p class="text-ink-700">{{ L(T.doneNote) }}</p>
      <p class="mt-2 text-sm text-ink-500">{{ form.service }} · OPTIZONE {{ form.branch }} · {{ form.day }} · {{ form.slot }}</p>
      <NuxtLink to="/" class="mt-6 inline-block rounded-sm bg-pine-700 px-6 py-3 font-display text-sm text-cream-100 hover:bg-amber-600 hover:text-pine-950">{{ L(T.backHome) }}</NuxtLink>
    </div>

    <!-- FORM -->
    <div v-else class="mx-auto grid max-w-container gap-8 px-7 py-10 lg:grid-cols-[1fr_320px] lg:items-start">
      <div class="flex flex-col gap-6">
        <div>
          <div class="mb-2.5 font-display text-[12px] uppercase tracking-[0.12em] text-ink-400">1 · {{ L(T.s1) }}</div>
          <div class="flex flex-wrap gap-2.5">
            <button v-for="s in services" :key="L(s)" @click="form.service = L(s)" class="rounded-pill border px-4 py-2 text-sm transition-colors" :class="form.service === L(s) ? 'border-pine-700 bg-pine-700 text-cream-100' : 'border-hair bg-white text-ink-700 hover:border-pine-400'">{{ L(s) }}</button>
          </div>
        </div>
        <div>
          <div class="mb-2.5 font-display text-[12px] uppercase tracking-[0.12em] text-ink-400">2 · {{ L(T.s2) }}</div>
          <div class="flex flex-wrap gap-2.5">
            <button v-for="b in branches" :key="b.name" @click="form.branch = b.name" class="rounded-pill border px-4 py-2 text-sm transition-colors" :class="form.branch === b.name ? 'border-pine-700 bg-pine-700 text-cream-100' : 'border-hair bg-white text-ink-700 hover:border-pine-400'">OPTIZONE {{ L({ en: b.name, he: b.he }) || b.name }}</button>
          </div>
        </div>
        <div>
          <div class="mb-2.5 font-display text-[12px] uppercase tracking-[0.12em] text-ink-400">3 · {{ L(T.s3) }}</div>
          <div class="flex flex-wrap gap-2.5">
            <button v-for="d in days" :key="d" @click="form.day = d" class="rounded-sm border px-4 py-2 text-sm transition-colors" :class="form.day === d ? 'border-pine-700 bg-pine-700 text-cream-100' : 'border-hair bg-white text-ink-700 hover:border-pine-400'">{{ d }}</button>
          </div>
        </div>
        <div>
          <div class="mb-2.5 font-display text-[12px] uppercase tracking-[0.12em] text-ink-400">4 · {{ L(T.s4) }}</div>
          <div class="flex flex-wrap gap-2.5">
            <button v-for="sl in slots" :key="sl" @click="form.slot = sl" class="rounded-sm border px-4 py-2 text-sm transition-colors" :class="form.slot === sl ? 'border-pine-700 bg-pine-700 text-cream-100' : 'border-hair bg-white text-ink-700 hover:border-pine-400'">{{ sl }}</button>
          </div>
        </div>
        <div class="grid gap-3 sm:grid-cols-2">
          <input v-model="form.name" :placeholder="L(T.fullName)" class="rounded-sm border border-hair px-3.5 py-3 text-sm" />
          <input v-model="form.phone" :placeholder="L(T.phone)" class="rounded-sm border border-hair px-3.5 py-3 text-sm" />
        </div>
        <p v-if="err" role="alert" class="text-[13px] text-red-500">{{ err }}</p>
      </div>

      <!-- summary -->
      <div class="rounded-lg border border-hair bg-white p-6 lg:sticky lg:top-24">
        <div class="mb-4 font-display text-sm uppercase tracking-[0.1em] text-ink-900">{{ L(T.summary) }}</div>
        <dl class="flex flex-col gap-2.5 text-sm">
          <div class="flex justify-between gap-3"><dt class="text-ink-400">{{ L(T.s1) }}</dt><dd class="text-end text-ink-900">{{ form.service || '—' }}</dd></div>
          <div class="flex justify-between gap-3"><dt class="text-ink-400">{{ L(T.s2) }}</dt><dd class="text-end text-ink-900">{{ form.branch || '—' }}</dd></div>
          <div class="flex justify-between gap-3"><dt class="text-ink-400">{{ L(T.s3) }}</dt><dd class="text-end text-ink-900">{{ form.day || '—' }}</dd></div>
          <div class="flex justify-between gap-3"><dt class="text-ink-400">{{ L(T.s4) }}</dt><dd class="text-end text-ink-900">{{ form.slot || '—' }}</dd></div>
        </dl>
        <button @click="submit" :disabled="busy" class="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-sm bg-pine-700 px-6 py-3.5 font-display text-sm uppercase tracking-wide text-cream-100 transition hover:bg-amber-600 hover:text-pine-950 disabled:opacity-60"><Calendar :size="17" /> {{ L(T.confirm) }}</button>
        <p class="mt-3 text-center text-[12.5px] text-ink-400">{{ L(T.noPay) }}</p>
      </div>
    </div>
  </div>
</template>
