// web/pages/cart.vue
<script setup lang="ts">
import { Trash2, Minus, Plus, Glasses } from 'lucide-vue-next'
const { L } = useLang()
const { t } = useT()
const tc = computed(() => t('cart'))
const { content } = useContent()
const { cart, setQty, remove, subtotal } = useCart()

const settings = computed(() => content.value?.settings || {})
const threshold = computed(() => settings.value.shippingThreshold ?? 400)
const fee = computed(() => settings.value.shippingFee ?? 30)

// Promo codes (Admin → Discounts). Applying a valid, active code discounts the
// subtotal by its percentage. The server never trusts client discounts — this is
// a display convenience only (server recomputes on order).
const promoInput = ref('')
const promo = ref<{ code: string; percent: number } | null>(null)
const promoErr = ref('')
const applyPromo = () => {
  const code = promoInput.value.trim().toUpperCase()
  if (!code) return
  const match = (settings.value.promos || []).find((p: any) => p.active !== false && String(p.code || '').toUpperCase() === code)
  if (match) { promo.value = { code, percent: Number(match.percent) || 0 }; promoErr.value = '' }
  else { promo.value = null; promoErr.value = tc.value.promoInvalid }
}
const discount = computed(() => (promo.value ? Math.round(subtotal.value * (promo.value.percent / 100)) : 0))
const shipping = computed(() => ((subtotal.value - discount.value) > threshold.value || subtotal.value === 0 ? 0 : fee.value))
const grandTotal = computed(() => subtotal.value - discount.value + shipping.value)
const fmt = (n: number) => Number(n).toLocaleString('he-IL')

useHead({ title: 'Cart — OPTIZONE' })
</script>

<template>
  <div v-if="cart.length === 0" class="mx-auto max-w-xl px-7 py-24 text-center">
    <Glasses :size="56" class="mx-auto text-pine-300" />
    <h1 class="mb-2 mt-5 font-display text-3xl font-medium text-ink-900">{{ tc.emptyH1 }}</h1>
    <p class="mb-6 text-ink-500">{{ tc.emptyP }}</p>
    <NuxtLink to="/eyeglasses" class="inline-block rounded-sm bg-pine-700 px-7 py-3.5 font-display text-sm uppercase tracking-wide text-cream-100 transition hover:bg-amber-600 hover:text-pine-950">{{ tc.shop }}</NuxtLink>
  </div>

  <div v-else class="mx-auto max-w-container px-7 pb-20 pt-9">
    <h1 class="mb-6 font-display text-4xl font-medium text-ink-900">{{ tc.title }}</h1>
    <div class="grid gap-9 lg:grid-cols-[1fr_340px] lg:items-start">
      <!-- LINES -->
      <div class="flex flex-col gap-3.5">
        <div v-for="(it, idx) in cart" :key="idx" class="flex items-center gap-4 rounded-md border border-hair bg-white p-4">
          <div class="flex h-[92px] w-[92px] flex-none items-center justify-center overflow-hidden rounded-sm bg-cream-300">
            <img v-if="it.image" :src="it.image" :alt="it.name" loading="lazy" class="h-full w-full object-cover" />
            <Glasses v-else :size="26" class="text-pine-500" />
          </div>
          <div class="flex-1">
            <div class="font-display text-[11px] uppercase tracking-[0.14em] text-amber-700">{{ it.brand }}</div>
            <div class="my-1 text-base font-semibold text-ink-900">{{ it.name }}</div>
            <div class="text-[13px] text-ink-500">{{ tc.lineNote }}</div>
            <div v-if="it.customSize" class="mt-0.5 text-[12.5px] text-amber-700">{{ tc.customSize(it.customSize) }}</div>
          </div>
          <div class="flex items-center gap-1 rounded-sm border border-hair">
            <button @click="setQty(idx, it.qty - 1)" aria-label="decrease" class="flex h-8 w-8 items-center justify-center text-ink-600 hover:text-pine-700"><Minus :size="14" /></button>
            <span class="w-6 text-center text-sm">{{ it.qty }}</span>
            <button @click="setQty(idx, it.qty + 1)" aria-label="increase" class="flex h-8 w-8 items-center justify-center text-ink-600 hover:text-pine-700"><Plus :size="14" /></button>
          </div>
          <div class="w-24 text-end font-display text-ink-900">₪{{ fmt(it.amount * it.qty) }}</div>
          <button @click="remove(idx)" aria-label="remove" class="text-ink-300 hover:text-red-500"><Trash2 :size="18" /></button>
        </div>
      </div>

      <!-- SUMMARY -->
      <div class="rounded-lg border border-hair bg-white p-6 lg:sticky lg:top-24">
        <div class="mb-4 font-display text-sm uppercase tracking-[0.1em] text-ink-900">{{ tc.summary }}</div>
        <div class="flex justify-between py-2 text-sm text-ink-700"><span>{{ tc.subtotal }}</span><span>₪{{ fmt(subtotal) }}</span></div>
        <div class="flex justify-between py-2 text-sm text-ink-700"><span>{{ tc.shipping }}</span><span>{{ shipping ? '₪' + shipping : tc.free }}</span></div>
        <div v-if="promo" class="flex justify-between py-2 text-sm text-emerald-700"><span>{{ tc.promoApplied(promo.code) }} · −{{ promo.percent }}%</span><span>−₪{{ fmt(discount) }}</span></div>
        <div class="my-3 flex gap-2">
          <input v-model="promoInput" :placeholder="tc.promo" @keydown.enter="applyPromo" class="flex-1 rounded-sm border border-hair px-3 py-2 text-sm" />
          <button @click="applyPromo" class="rounded-sm border border-pine-700 px-3 py-2 text-sm text-pine-700 hover:bg-pine-50">{{ tc.apply }}</button>
        </div>
        <p v-if="promoErr" role="alert" class="mb-2 text-[12.5px] text-red-500">{{ promoErr }}</p>
        <div class="my-3 border-t border-hair" />
        <div class="flex items-baseline justify-between">
          <span class="font-display text-[15px] uppercase tracking-[0.06em] text-ink-900">{{ tc.total }}</span>
          <span class="font-display text-2xl text-ink-900">₪{{ fmt(grandTotal) }}</span>
        </div>
        <div class="mt-5 flex flex-col gap-2.5">
          <NuxtLink to="/checkout" class="rounded-sm bg-pine-700 px-6 py-3.5 text-center font-display text-sm uppercase tracking-wide text-cream-100 transition hover:bg-amber-600 hover:text-pine-950">{{ tc.checkout }}</NuxtLink>
          <NuxtLink to="/booking" class="rounded-sm px-6 py-2.5 text-center font-display text-sm text-pine-700 hover:text-amber-700">{{ tc.reserve }}</NuxtLink>
        </div>
        <div class="mt-4 flex flex-wrap justify-center gap-3.5 font-display text-[11px] uppercase tracking-[0.08em] text-ink-300">
          <span v-for="pm in tc.pays" :key="pm">{{ pm }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

// src/pages/Cart.jsx
import React, { useState } from 'react'
import { Button, Icon, QuantityStepper, Price, Card, Input, GlassesMark } from '../ds/index.js'
import { useLang } from '../i18n/index.jsx'
import { useContent } from '../content/ContentProvider.jsx'

export function Cart({ cart, setCart, go, openCatalog }) {
  const t = useLang().t.cart
  const s = useContent().content.settings || {}
  const threshold = s.shippingThreshold ?? 400
  const fee = s.shippingFee ?? 30
  const subtotal = cart.reduce((sum, i) => sum + i.amount * i.qty, 0)
  // Promo codes are managed in Admin → Discounts (settings.promos). Applying a
  // valid, active code discounts the subtotal by its percentage.
  const [promoInput, setPromoInput] = useState('')
  const [promo, setPromo] = useState(null) // { code, percent }
  const [promoErr, setPromoErr] = useState('')
  const applyPromo = () => {
    const code = promoInput.trim().toUpperCase()
    if (!code) return
    const match = (s.promos || []).find((p) => p.active !== false && String(p.code || '').toUpperCase() === code)
    if (match) { setPromo({ code, percent: Number(match.percent) || 0 }); setPromoErr('') }
    else { setPromo(null); setPromoErr(t.promoInvalid) }
  }
  const discount = promo ? Math.round(subtotal * (promo.percent / 100)) : 0
  const shipping = (subtotal - discount) > threshold || subtotal === 0 ? 0 : fee
  const setQty = (idx, qty) => setCart(cart.map((c, i) => (i === idx ? { ...c, qty } : c)))
  const remove = (idx) => setCart(cart.filter((_, i) => i !== idx))

  if (cart.length === 0) {
    return (
      <div style={{ maxWidth: 560, margin: '80px auto 120px', textAlign: 'center', padding: '0 28px' }}>
        <GlassesMark size={64} color="var(--pine-300)" />
        <h1 style={{ fontFamily: 'var(--font-display)', fontWeight: 500, fontSize: 30, color: 'var(--text-strong)', margin: '20px 0 8px' }}>{t.emptyH1}</h1>
        <p style={{ color: 'var(--text-muted)', marginBottom: 22 }}>{t.emptyP}</p>
        <Button variant="primary" size="lg" onClick={() => openCatalog('eyeglasses')}>{t.shop}</Button>
      </div>
    )
  }

  return (
    <div style={{ maxWidth: 'var(--container-max)', margin: '0 auto', padding: '36px 28px 80px' }}>
      <h1 style={{ fontFamily: 'var(--font-display)', fontWeight: 500, fontSize: 34, color: 'var(--text-strong)', margin: '0 0 24px' }}>{t.title}</h1>
      <div className="oz-sidebar" style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 36, alignItems: 'start' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {cart.map((it, idx) => (
            <div key={idx} className="oz-cart-item" style={{ display: 'flex', gap: 18, padding: 16, background: 'var(--surface-card)', border: '1px solid var(--border-hair)', borderRadius: 'var(--radius-md)', alignItems: 'center' }}>
              <div style={{ width: 92, height: 92, borderRadius: 'var(--radius-sm)', background: 'var(--cream-300)', display: 'flex', alignItems: 'center', justifyContent: 'center', flex: '0 0 auto', overflow: 'hidden' }}>
                {it.image
                  ? <img src={it.image} alt={it.name} loading="lazy" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                  : <GlassesMark size={26} color={(it.colors && it.colors[0]) || 'var(--pine-500)'} />}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'var(--font-display)', fontSize: 11, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--text-accent)' }}>{it.brand}</div>
                <div style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-strong)', margin: '3px 0 6px' }}>{it.name}</div>
                <div style={{ fontSize: 13, color: 'var(--text-muted)' }}>{t.lineNote}</div>
                {/* Try Mirror custom frame size follows the line item */}
                {it.customSize && <div style={{ fontSize: 12.5, color: 'var(--text-accent)', marginTop: 3 }}>{t.customSize(it.customSize)}</div>}
              </div>
              <QuantityStepper value={it.qty} onChange={(q) => setQty(idx, q)} size="sm" />
              <div style={{ width: 90, textAlign: 'end' }}><Price amount={it.amount * it.qty} /></div>
              <button onClick={() => remove(idx)} aria-label="remove" style={{ border: 'none', background: 'transparent', cursor: 'pointer', color: 'var(--text-faint)' }}><Icon name="trash-2" size={18} /></button>
            </div>
          ))}
        </div>

        <Card padding="lg" style={{ position: 'sticky', top: 96 }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 14, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--text-strong)', marginBottom: 16 }}>{t.summary}</div>
          {[[t.subtotal, `₪${subtotal.toLocaleString('he-IL')}`], [t.shipping, shipping ? `₪${shipping}` : t.free]].map(([k, v]) => (
            <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '9px 0', fontSize: 14, color: 'var(--text-body)' }}><span>{k}</span><span>{v}</span></div>
          ))}
          {promo && (
            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '9px 0', fontSize: 14, color: 'var(--success)' }}>
              <span>{t.promoApplied(promo.code)} · −{promo.percent}%</span><span>−₪{discount.toLocaleString('he-IL')}</span>
            </div>
          )}
          <div style={{ display: 'flex', gap: 8, margin: '12px 0' }}>
            <Input placeholder={t.promo} value={promoInput} onChange={(e) => setPromoInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && applyPromo()} containerStyle={{ flex: 1 }} size="sm" />
            <Button variant="outline" size="sm" onClick={applyPromo}>{t.apply}</Button>
          </div>
          {promoErr && <div role="alert" style={{ fontSize: 12.5, color: 'var(--danger)', marginBottom: 8 }}>{promoErr}</div>}
          <div style={{ borderTop: '1px solid var(--border-hair)', margin: '8px 0 14px' }} />
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
            <span style={{ fontFamily: 'var(--font-display)', fontSize: 15, letterSpacing: '0.06em', color: 'var(--text-strong)' }}>{t.total}</span>
            <Price amount={subtotal - discount + shipping} size="lg" />
          </div>
          <div style={{ marginTop: 16, display: 'flex', flexDirection: 'column', gap: 10 }}>
            <Button variant="primary" block size="lg" onClick={() => go('checkout')}>{t.checkout}</Button>
            <Button variant="ghost" block onClick={() => go('booking')}>{t.reserve}</Button>
          </div>
          <div style={{ display: 'flex', justifyContent: 'center', gap: 14, marginTop: 14, fontSize: 11, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--text-faint)', fontFamily: 'var(--font-display)', flexWrap: 'wrap' }}>
            {t.pays.map((pm) => <span key={pm}>{pm}</span>)}
          </div>
        </Card>
      </div>
    </div>
  )
}
